-- Schema: beetles (release records)
create table if not exists public.beetles (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  head text not null,
  body text not null,
  pattern text not null,
  primary_color text not null,
  secondary_color text,
  iridescence boolean not null,
  gloss boolean not null,
  user_id uuid
);

-- Index for latest-first reads
create index if not exists beetles_created_at_idx on public.beetles (created_at desc);

-- Enable RLS and allow public read/insert (good for kiosk/demo)
alter table public.beetles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'beetles' and policyname = 'public_insert'
  ) then
    create policy "public_insert" on public.beetles
      for insert to anon
      with check (true);
  end if;
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'beetles' and policyname = 'public_read'
  ) then
    create policy "public_read" on public.beetles
      for select to anon
      using (true);
  end if;
end$$;

